---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
  namespace: demo
data:
  index.html: |
    <html>
    <head><title>Web Server</title></head>
    <body>
      <h1>Welcome to the Web Server!</h1>
      <p>Pod IP: $POD_IP</p>
      <p id="serving-host">serving-host=Host-XXXXX</p>
    </body>
    </html>

  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }