apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      # Init Container modifies HTML before startup
      initContainers:
      - name: init-html
        image: busybox
        command:
          - sh
          - -c
          - |
            cp /config/index.html /workdir/index.html
            pod_name=$(hostname)
            host_suffix=${pod_name: -5}
            sed -i "s/Host-XXXXX/Host-${host_suffix}/g" /workdir/index.html
            sed -i "s/\$POD_IP/${POD_IP}/g" /workdir/index.html
        volumeMounts:
        - name: html
          mountPath: /workdir
        - name: config
          mountPath: /config
          readOnly: true

      # Nginx main container serves customized HTML
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: config
          subPath: default.conf
          mountPath: /etc/nginx/conf.d/default.conf

      volumes:
      - name: html
        emptyDir: {}           # shared writable space
      - name: config
        configMap:
          name: webserver-config
