apiVersion: v1
kind: Service
metadata:
  name: web-server-svc
  namespace: demo
spec:
  type: NodePort   # Use LoadBalancer if you're on cloud (GKE, EKS, AKS)
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
