replicaCount: 1

image:
  repository: 729874396527.dkr.ecr.us-east-1.amazonaws.com/pod-monitor
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

serviceAccount:
  create: true
  name: pod-monitor-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::729874396527:role/pod-monitor-ecr-role

namespace: default
