replicaCount: 1

image:
  repository: pod-monitor
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

serviceAccount:
  create: true
  name: pod-monitor-sa

namespace: default
