name: Terraform Deploy

on:
  workflow_dispatch:           # Only manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}  # Checkout the selected branch

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::729874396527:role/github_oidc
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init & Apply
        working-directory: k8s_aws_cluster
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4  # or latest stable

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name demo-eks-cluster

      - name: Deploy MariaDB via Helm
        working-directory: deployments/database
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
          MARIADB_REPLICATION_PASSWORD: ${{ secrets.MARIADB_REPLICATION_PASSWORD }}
          MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
          MARIADB_USER: ${{ secrets.MARIADB_USER }}
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        run: |
          helm upgrade --install mariadb ./mariadb -f mariadb_values.yaml \
            --namespace demo \
            --create-namespace \
            --set auth.rootPassword="$MARIADB_ROOT_PASSWORD" \
            --set auth.replicationPassword="$MARIADB_REPLICATION_PASSWORD" \
            --set auth.database="$MARIADB_DATABASE" \
            --set auth.username="$MARIADB_USER" \
            --set auth.password="$MARIADB_PASSWORD"